_build/bin/dockerd usr/sbin/

engine/contrib/check-config.sh                usr/share/docker.io/contrib/
engine/contrib/dockerd-rootless.sh            usr/share/docker.io/contrib/
engine/contrib/dockerd-rootless-setuptool.sh  usr/share/docker.io/contrib/
engine/contrib/nuke-graph-directory.sh        usr/share/docker.io/contrib/

## libnetwork:
_build/bin/docker-proxy  usr/sbin/

debian/etc/daemon.json etc/docker/
